# -*- coding: utf-8 -*-
"""perhitungan_Ann(09020624047).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yek4KwOchII5j_OSXrZQAzbaQba248Y3

Nama: M. Atsiil Ukasyah
NIM : 09020624047
"""

import numpy as np
import pandas as pd

"""mengimpor library, numpy untuk menghitung dan pandas untuk membaca fie excel."""

df = pd.read_excel("diabetes.xlsx")
print(df.head())

X = df.drop("Outcome", axis=1).values   # Fitur  (768 x 8)
y = df["Outcome"].values.reshape(1, -1) # Label  (1  x 768)

"""kode diatas membaca file dengan pd.read_excel kemudian menamilkan lima baris pertama dengan df.head(), kemudian di X menghapus kolom "Outcome" dan dilakukan pada kolom(axis=1), kemudian mengubah DataFrame hasil menjadi array NumPy 2D dengan values. dan asilnya X berdimensi (768, 8), yaitu 768 sampel (baris) dan 8 fitur (kolom), kemudian di Y mengambel kolom "Outcome" sebagai aray 1d dengan panjang 768, dan mengubah menjadi baris tunggal (2D dengan 1 baris dan 768 kolom). Jadi y berdimensi (1, 768).

"""

# Normalisasi Min-Max  →  nilai jadi 0 s/d 1
X = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0) + 1e-8)
np.set_printoptions(suppress=True, precision=4)
print("hasil normalisasi")
print(X)

np.random.seed(42)
idx   = np.random.permutation(X.shape[0])#Menghasilkan array berisi urutan angka 0 sampai 767 yang diacak. hingga x.shape(768)
split = int(0.8 * len(idx))#membagi data menjadi 80% untuk latihan dan sisanya untuk data uji.

X_train = X[idx[:split]].T   ;  y_train = y[:, idx[:split]]
X_test  = X[idx[split:]].T   ;  y_test  = y[:, idx[split:]]

"""kode diatas, untuk rumus(X - X.min(axis=0)) Menghitung nilai minimum setiap kolom (fitur), menghasilkan array 1D dengan panjang 8 (sesuai jumlah fitur), dan untuk X.max untuk menghitung nilai maksimum yang kemudian dikurangi Xmin, dan ditambah 1e-8 yang merupakan bilangan kecil (0,00000001), kemudian hasilnya ditampilkan dengan mengubahnya menjadi bilangan desimal(supress=true) dan membatasi koma sekitar hanya 4 nomer, kemudian Menetapkan seed generator bilangan acak agar pengacakan selalu sama setiap kali kode dijalankan (reproducible)(42), X[idx[:split]] berfungsi untuk Mengambil 614 baris dari X sesuai indeks latih, hasilnya array 2D berukuran (614, 8).T (transpose) untuk Mengubahnya menjadi (8, 614). Jadi setiap baris sekarang mewakili satu fitur, dan kolom mewakili sampel."""

def initialize_parameters(input_size, hidden_size, output_size):#input_size=Jumlah neuron pada input layer, yaitu jumlah fitur, hidden_size= jumlah neuron pada hidden layer, dan putput_size=jumlah neuron pada outcome.
    np.random.seed(42)
    parameters = {
        "W1": np.random.randn(hidden_size, input_size) * 0.01,
        "b1": np.zeros((hidden_size, 1)),
        "W2": np.random.randn(output_size, hidden_size) * 0.01,
        "b2": np.zeros((output_size, 1))
    }
    return parameters

"""kode diatas membuat parameters dengan isi W1 Membuat matriks dengan bentuk(hidden_size × input_size) berisi angka acak dari distribusi normal standar (rata-rata 0, standar deviasi 1), kemudian dikalikan 0.01. Sedikit berbeda untuk W2 yang membuat matriks bobot untuk hidden output, bentuk (output_size × hidden_size). kemudian untuk b1, Vektor kolom nol sejumlah hidden_size. Bentuk (hidden_size, 1), sedangka b2 output_siza."""

def sigmoid(Z):
    return 1 / (1 + np.exp(-Z))

def relu(Z):
    return np.maximum(0, Z)

def relu_derivative(Z):
    return (Z > 0).astype(int)

"""kode diatas, untuk Fungsi sigmoid(Z) menghitung 1/(1+eksponen -z)
dan menghasilkan nilai antara 0 dan 1, cocok sebagai aktivasi output layer untuk klasifikasi biner karena mewakili probabilitas; relu(Z) mengembalikan nilai maksimum antara 0 dan Z (dengan np.maximum(0, Z)), yang mempercepat pelatihan dan mengurangi vanishing gradient di hidden layer; sementara relu_derivative(Z) menghasilkan turunan ReLU, yaitu 1 untuk Z > 0 dan 0 untuk Z ≤ 0, yang diperoleh dengan (Z > 0).astype(int), dan digunakan saat backpropagation untuk menghitung gradien error terhadap Z di hidden layer.

"""

def forward_propagation(X, parameters):
    W1, b1 = parameters["W1"], parameters["b1"]
    W2, b2 = parameters["W2"], parameters["b2"]

    Z1 = np.dot(W1, X) + b1   # Hidden layer  : linear
    A1 = relu(Z1)              # Hidden layer  : ReLU
    Z2 = np.dot(W2, A1) + b2  # Output layer  : linear
    A2 = sigmoid(Z2)           # Output layer  : Sigmoid, probabilitas

    cache = {"Z1": Z1, "A1": A1, "Z2": Z2, "A2": A2}
    return A2, cache

"""kode diatas berfungsi forward_propagation(X, parameters) menjalankan langkah maju (forward pass) pada neural network dua layer dengan menerima matriks fitur X berdimensi (input_size, jumlah_sampel) dan dictionary parameters yang berisi W1, b1, W2, b2; pertama, ia menghitung Z1 = np.dot(W1, X) + b1 sebagai kombinasi linear di hidden layer (menghasilkan array (hidden_size, m)) lalu menerapkan aktivasi ReLU A1 = relu(Z1) untuk memperkenalkan non-linearitas, kemudian menghitung Z2 = np.dot(W2, A1) + b2 untuk output layer (berdimensi (1, m)) dan mengonversinya menjadi probabilitas antara 0–1 melalui A2 = sigmoid(Z2). Seluruh nilai antara (Z1, A1, Z2, A2) disimpan dalam cache dan dikembalikan bersama A2 sebagai prediksi akhir"""

def compute_cost(Y, A2):
    m    = Y.shape[1]
    cost = -np.sum(Y * np.log(A2 + 1e-8) + (1 - Y) * np.log(1 - A2 + 1e-8)) / m
    return np.squeeze(cost)

"""Fungsi compute_cost(Y, A2) menghitung biaya (cost) model pada data dengan menggunakan rumus binary cross-entropy loss antara label sebenarnya Y dan prediksi probabilitas A2 (keluaran dari forward_propagation). Variabel m = Y.shape[1] mengambil jumlah total sampel pada batch/data (karena Y berdimensi (1, m)), kemudian fungsi menghitung rata-rata dari - [ Y * log(A2) + (1 - Y) * log(1 - A2) ] untuk semua sampel. kemudian hasil disimpan ke-np.squeeze(cost)"""

def backward_propagation(X, Y, parameters, cache):
    m  = X.shape[1]
    W2 = parameters["W2"]

    dZ2 = cache["A2"] - Y
    dW2 = np.dot(dZ2, cache["A1"].T) / m
    db2 = np.sum(dZ2, axis=1, keepdims=True) / m

    dZ1 = np.dot(W2.T, dZ2) * relu_derivative(cache["Z1"])
    dW1 = np.dot(dZ1, X.T) / m
    db1 = np.sum(dZ1, axis=1, keepdims=True) / m

    grads = {"dW1": dW1, "db1": db1, "dW2": dW2, "db2": db2}
    return grads

"""kode diatas, Fungsi backward_propagation(X, Y, parameters, cache) menjalankan langkah mundur (backward pass) untuk menghitung gradien seluruh parameter terhadap fungsi biaya binary cross-entropy. Dimulai dengan menghitung dZ2 = cache["A2"] - Y, yang merupakan turunan langsung dari loss sigmoid terhadap Z2, kemudian gradien bobot dan bias output diperoleh melalui dW2 = np.dot(dZ2, cache["A1"].T) / m serta db2 = np.sum(dZ2, axis=1, keepdims=True) / m (dirata‑rata atas m sampel). Selanjutnya galat dialirkan ke hidden layer dengan dZ1 = np.dot(W2.T, dZ2) * relu_derivative(cache["Z1"]), yang mengalikan propagasi mundur dari output dengan turunan ReLU untuk hanya meneruskan galat pada neuron yang aktif (Z1 > 0), lalu gradien dW1 dan db1 dihitung serupa menggunakan X dan cache["Z1"] kemudian dikembalikan dalam grads"""

def update_parameters(parameters, grads, learning_rate):
    for key in parameters.keys():
        parameters[key] -= learning_rate * grads["d" + key]
    return parameters

"""kode diatas, pada Fungsi update_parameters(parameters, grads, learning_rate) untuk memperbarui semua bobot dan bias yang tersimpan di parameters. Ia melakukan iterasi melalui setiap kunci (misalnya "W1", "b1", "W2", "b2"), lalu mengurangi nilai parameter saat ini dengan hasil perkalian learning_rate * grads["d" + key], di mana "d" + key menghasilkan yang sesuai ("dW1", "db1", "dW2", "db2") dari grads yang telah dihitung pada langkah backpropagation. kemudian dikembalikan ke parameters"""

def train(X, Y, hidden_size=16, learning_rate=0.1, epochs=2000):
    parameters   = initialize_parameters(X.shape[0], hidden_size, 1)
    cost_history = []

    for i in range(1, epochs + 1):
        A2, cache  = forward_propagation(X, parameters)
        cost       = compute_cost(Y, A2)
        grads      = backward_propagation(X, Y, parameters, cache)
        parameters = update_parameters(parameters, grads, learning_rate)
        cost_history.append(cost)

        if i % 200 == 0 or i == 1:
            acc = np.mean((A2 >= 0.5) == Y) * 100
            print(f"Epoch {i:5d}  |  Loss: {cost:.4f}  |  Akurasi: {acc:.2f}%")

    return parameters, cost_history

"""kode diatas, Fungsi train(X, Y, hidden_size=16, learning_rate=0.1, epochs=2000) menjalankan pelatihan. Pertama, ia menginisialisasi parameter W1, b1, W2, b2 melalui initialize_parameters dengan ukuran input diambil dari X.shape[0], hidden_size (default 16 neuron), dan output 1 (klasifikasi biner). Selanjutnya, dalam loop sebanyak epochs dimulai dari 1, fungsi melakukan forward propagation untuk mendapatkan prediksi A2 serta cache, lalu menghitung biaya (loss) menggunakan compute_cost dengan binary cross-entropy, dilanjutkan backward propagation untuk memperoleh gradien dW1, db1, dW2, db2, dan memperbarui parameter dengan update_parameters serta learning rate. Riwayat biaya dari setiap epoch disimpan ke dalam list cost_history. Setiap 200 epoch atau pada epoch pertama, akurasi dihitung dengan membandingkan (A2 >= 0.5) terhadap label Y, dan dicetak bersama loss dalam format yang mudah dipantau. Setelah seluruh epoch selesai, fungsi mengembalikan parameter terlatih dan rekaman biaya, yang dapat digunakan untuk evaluasi atau analisis konvergensi pelatihan."""

def predict(X, parameters):
    A2, _ = forward_propagation(X, parameters)
    return (A2 >= 0.5).astype(int)

parameters, cost_history = train(X_train, y_train)

y_pred_train = predict(X_train, parameters)
y_pred_test  = predict(X_test,  parameters)
acc_train    = np.mean(y_pred_train == y_train) * 100
acc_test     = np.mean(y_pred_test  == y_test)  * 100
print(f"\nAkurasi Data Latih : {acc_train:.2f}%")
print(f"Akurasi Data Uji   : {acc_test:.2f}%")

"""kode diatas, pada Fungsi predict(X, parameters) melakukan forward propagation untuk menghasilkan probabilitas A2, lalu mengubahnya menjadi label biner dengan ambang 0,5 menggunakan (A2 >= 0.5).astype(int), sehingga nilai ≥50% menjadi 1 dan sisanya 0. Model dilatih melalui train(X_train, y_train) menggunakan data latih yang telah dinormalisasi (80% dari 768 sampel), menghasilkan parameter optimal dan riwayat loss selama 2000 epoch. Parameter tersebut kemudian dipakai untuk memprediksi data latih dan uji, sedangkan akurasi dihitung dari kecocokan prediksi dengan label asli."""

# Ambil probabilitas kelas 1 (diabetes)
proba_diabetes, _ = forward_propagation(X_test, parameters)

target = y_test[0, 0]
proba_1 = proba_diabetes[0, 0]          # probabilitas diabetes
pred = 1 if proba_1 >= 0.5 else 0       # kelas hasil prediksi
if pred == 1:
    confidence = proba_1 * 100          # persen keyakinan kelas 1
else:
    confidence = (1 - proba_1) * 100    # persen keyakinan kelas 0

print(f"Target asli (data uji pertama)       : {target}")
print(f"Probabilitas diabetes (kelas 1)      : {proba_1:.4f} ({proba_1*100:.2f}%)")
print(f"Probabilitas TIDAK diabetes (kelas 0): {1-proba_1:.4f} ({(1-proba_1)*100:.2f}%)")
print(f"Hasil prediksi AI                    : {pred}")
print(f"Keyakinan model terhadap kelas {pred} : {confidence:.2f}%")

"""kode diatas pada fungsi forward_propagation(X_test, parameters) dilakukan untuk mendapatkan probabilitas diabetes seluruh sampel uji, lalu mengambil label asli target = y_test[0,0] dan probabilitas proba_1 = proba_diabetes[0,0] dari sampel indeks pertama, setelah menentukan kelas prediksi pred (1 jika proba_1 >= 0.5, selain itu 0), keyakinan model dihitung sebagai proba_1 * 100 jika prediksi diabetes atau (1-proba_1)*100 jika prediksi non-diabetes. Selanjutnya, kode mencetak target asli beserta probabilitas lengkap kedua kelas (diabetes dan tidak diabetes), hasil prediksi AI, dan tingkat keyakinan model terhadap kelas yang diprediksi, sehingga memberi interpretasi intuitif tentang keputusan jaringan untuk satu pasien individu."""